[package]
name = "trc"
version = "1.1.7"
edition = "2021"
license = "MIT"
readme = "README.md"
authors = ["Eric Buehler"]
description = "A smart pointer that implements biased reference counting to outperform Arc and allow thread-safety."
homepage = "https://github.com/EricLBuehler/trc"
repository = "https://github.com/EricLBuehler/trc"
keywords = ["reference-counted", "thread-safe", "smart-pointer", "memory"]
categories = ["memory-management", "data-structures", "concurrency"]

[dependencies]
