name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test atomic
      run: cargo test --features force_atomic --no-default-features
    - name: Test default
      run: cargo test

  miri:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Miri
      run:  rustup +nightly component add miri
    - name: Test atomic with Miri
      run: cargo +nightly miri test --features force_atomic --no-default-features
    - name: Test default with Miri
      run: cargo +nightly miri test